wip

diff --git a/.config/yadm/bootstrap##template b/.config/yadm/bootstrap##template
--- a/.config/yadm/bootstrap##template
+++ b/.config/yadm/bootstrap##template
@@ -7,13 +7,13 @@ set -eu
 {% if yadm.os == "Darwin" %}
 # install homebrew if it's missing
 if ! command -v brew >/dev/null 2>&1; then
-    echo "Installing homebrew"
-    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+	echo "Installing homebrew"
+	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
 fi
 
 if [ -f "$HOME/.Brewfile" ]; then
-    echo "Updating homebrew bundle"
-    brew bundle --global
+	echo "Updating homebrew bundle"
+	brew bundle --global
 fi
 {% endif %}
 
@@ -61,7 +61,7 @@ packages+=(
 	"yadm"
 	"zoxide"
 	"zsh-autosuggestions"
-	"zsh-syntax-highlighting"
+	# "zsh-syntax-highlighting"
 )
 {% endif %}
 
@@ -69,20 +69,20 @@ packages+=(
 BOOTSTRAP_D="${BASH_SOURCE[0]}.d"
 
 if [[ ! -d "$BOOTSTRAP_D" ]]; then
-    echo "Error: bootstrap directory '$BOOTSTRAP_D' not found" >&2
-    exit 1
+	echo "Error: bootstrap directory '$BOOTSTRAP_D' not found" >&2
+	exit 1
 fi
 
 # This will execute all executable files (excluding templates and editor
 # backups) in the $BOOTSTRAP_D directory when run.
 
 find -L "$BOOTSTRAP_D" -type f | sort | while IFS= read -r bootstrap; do
-    if [[ -x "$bootstrap" && ! "$bootstrap" =~ "##" && ! "$bootstrap" =~ "~$" ]]; then
-        if ! "$bootstrap"; then
-            echo "Error: bootstrap '$bootstrap' failed" >&2
-            exit 1
-        fi
-    fi
+	if [[ -x "$bootstrap" && ! "$bootstrap" =~ "##" && ! "$bootstrap" =~ "~$" ]]; then
+		if ! "$bootstrap"; then
+			echo "Error: bootstrap '$bootstrap' failed" >&2
+			exit 1
+		fi
+	fi
 done
 
 hash -r
@@ -95,12 +95,12 @@ npm install --global pure-prompt
 YARN=$(brew --prefix yarn)/bin/yarn
 
 if (command -v "$YARN" >/dev/null 2>&1); then
-    # Install yalc. Needed for local-publish
-    echo "Installing yalc..."
-    if ! $YARN global add yalc; then
-        echo "Failed to install yalc" >&2
-    else
-        echo "Successfully installed yalc"
-    fi
+	# Install yalc. Needed for local-publish
+	echo "Installing yalc..."
+	if ! $YARN global add yalc; then
+		echo "Failed to install yalc" >&2
+	else
+		echo "Successfully installed yalc"
+	fi
 fi
 {% endif %}
